// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudDataCatalogLineageV1
import GoogleLongRunning
import GoogleWKT

func sample(client: LineageClient, projectId: String, locationId: String, processId: String)
  async throws
{
  let response = try await client.updateProcess(
    request: UpdateProcessRequest()
      .with {
        $0.process = Process().with {
          $0.name = "projects/\(projectId)/locations/\(locationId)/processes/\(processId)"
        }
        $0.updateMask = GoogleWKT.WKTFieldMask(paths: ["field.path1", "field.path2"])
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudDataCatalogLineageV1.LineageClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        processId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
