// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The soft reference to everything you can attach a lineage event to.
public struct EntityReference: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. [Fully Qualified Name
  /// (FQN)](https://cloud.google.com/dataplex/docs/fully-qualified-names)
  /// of the entity.
  public var fullyQualifiedName: Swift.String = Swift.String()

  /// Optional. Field path within the entity. Each nesting level should be a
  /// separate value in the repeated field. The order matters. Must be empty for
  /// asset level lineage
  ///
  /// For example to address "salary.net" subfield where "salary" is a column and
  /// "net" is a proto field two values in the `field` should be reported,
  /// the first is "salary" and the second is "net".
  ///
  /// Each field length is limited to 500 characters.
  /// Maximum supported nesting level is 20.
  public var field: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EntityReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntityReference().with { $0.fullyQualifiedName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fullyQualifiedName = CodingKeys(stringValue: "fullyQualifiedName")
    static let field = CodingKeys(stringValue: "field")

    static let _knownKeys: Set<Swift.String> = [
      "fullyQualifiedName",
      "field",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullyQualifiedName) {
      self.fullyQualifiedName = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .field) {
      self.field = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fullyQualifiedName, forKey: .fullyQualifiedName)
    try container.encode(self.field, forKey: .field)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.EntityReference"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
