// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A lineage between source and target entities.
public struct EventLink: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Reference to the source entity
  public var source: EntityReference? = nil

  /// Required. Reference to the target entity
  public var target: EntityReference? = nil

  /// Optional. Describes how the target depends on the source.
  public var dependencyInfo: DependencyInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EventLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventLink().with { $0.source = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let source = CodingKeys(stringValue: "source")
    static let target = CodingKeys(stringValue: "target")
    static let dependencyInfo = CodingKeys(stringValue: "dependencyInfo")

    static let _knownKeys: Set<Swift.String> = [
      "source",
      "target",
      "dependencyInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.source = try container.decodeIfPresent(EntityReference.self, forKey: .source)
    self.target = try container.decodeIfPresent(EntityReference.self, forKey: .target)
    self.dependencyInfo = try container.decodeIfPresent(
      DependencyInfo.self, forKey: .dependencyInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encodeIfPresent(self.target, forKey: .target)
    try container.encodeIfPresent(self.dependencyInfo, forKey: .dependencyInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.EventLink"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
