// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class LineageLogging: LineageStub {
    let inner: any LineageStub
    let logger: Logger

    public init(_ inner: any LineageStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-datacatalog-lineage-v1"
      logger[metadataKey: "gcp.client.service"] = "datalineage"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Lineage"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func processOpenLineageRunEvent(
      request: ProcessOpenLineageRunEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "processOpenLineageRunEvent",
        action: {
          (r: ProcessOpenLineageRunEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse
          in
          return try await self.inner.processOpenLineageRunEvent(request: r, options: o)
        })
    }

    public func createProcess(
      request: CreateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
      try await self._intercept(
        request: request,
        options: options,
        name: "createProcess",
        action: {
          (r: CreateProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Process
          in
          return try await self.inner.createProcess(request: r, options: o)
        })
    }

    public func updateProcess(
      request: UpdateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateProcess",
        action: {
          (r: UpdateProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Process
          in
          return try await self.inner.updateProcess(request: r, options: o)
        })
    }

    public func getProcess(
      request: GetProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProcess",
        action: {
          (r: GetProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Process
          in
          return try await self.inner.getProcess(request: r, options: o)
        })
    }

    public func listProcesses(
      request: ListProcessesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProcesses",
        action: {
          (r: ListProcessesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse
          in
          return try await self.inner.listProcesses(request: r, options: o)
        })
    }

    public func deleteProcess(
      request: DeleteProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteProcess",
        action: {
          (r: DeleteProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteProcess(request: r, options: o)
        })
    }

    public func createRun(
      request: CreateRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRun",
        action: {
          (r: CreateRunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Run
          in
          return try await self.inner.createRun(request: r, options: o)
        })
    }

    public func updateRun(
      request: UpdateRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRun",
        action: {
          (r: UpdateRunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Run
          in
          return try await self.inner.updateRun(request: r, options: o)
        })
    }

    public func getRun(
      request: GetRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRun",
        action: {
          (r: GetRunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.Run
          in
          return try await self.inner.getRun(request: r, options: o)
        })
    }

    public func listRuns(
      request: ListRunsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRuns",
        action: {
          (r: ListRunsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.ListRunsResponse
          in
          return try await self.inner.listRuns(request: r, options: o)
        })
    }

    public func deleteRun(
      request: DeleteRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRun",
        action: {
          (r: DeleteRunRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRun(request: r, options: o)
        })
    }

    public func createLineageEvent(
      request: CreateLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
      try await self._intercept(
        request: request,
        options: options,
        name: "createLineageEvent",
        action: {
          (r: CreateLineageEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.LineageEvent
          in
          return try await self.inner.createLineageEvent(request: r, options: o)
        })
    }

    public func getLineageEvent(
      request: GetLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLineageEvent",
        action: {
          (r: GetLineageEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.LineageEvent
          in
          return try await self.inner.getLineageEvent(request: r, options: o)
        })
    }

    public func listLineageEvents(
      request: ListLineageEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLineageEvents",
        action: {
          (r: ListLineageEventsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse
          in
          return try await self.inner.listLineageEvents(request: r, options: o)
        })
    }

    public func deleteLineageEvent(
      request: DeleteLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteLineageEvent",
        action: {
          (r: DeleteLineageEventRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteLineageEvent(request: r, options: o)
        })
    }

    public func searchLinks(
      request: SearchLinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchLinks",
        action: {
          (r: SearchLinksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse
          in
          return try await self.inner.searchLinks(request: r, options: o)
        })
    }

    public func batchSearchLinkProcesses(
      request: BatchSearchLinkProcessesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchSearchLinkProcesses",
        action: {
          (r: BatchSearchLinkProcessesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse
          in
          return try await self.inner.batchSearchLinkProcesses(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
