// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Lineage link between two entities.
public struct LineageLink: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The entity that is the **source** of this link.
  public var source: EntityReference? = nil

  /// The entity that is the **target** of this link.
  public var target: EntityReference? = nil

  /// Processes metadata associated with the link.
  public var processes: [LineageLink.LineageProcess] = []

  /// Describes how the target entity is dependent on the source entity.
  public var dependencyInfo: [LineageLink.DependencyInfo] = []

  /// Depth of the current link in the graph starting from 1.
  public var depth: Swift.Int32 = Swift.Int32()

  /// The location where the LineageEvent that created the link is stored.
  public var location: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LineageLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineageLink().with { $0.source = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let source = CodingKeys(stringValue: "source")
    static let target = CodingKeys(stringValue: "target")
    static let processes = CodingKeys(stringValue: "processes")
    static let dependencyInfo = CodingKeys(stringValue: "dependencyInfo")
    static let depth = CodingKeys(stringValue: "depth")
    static let location = CodingKeys(stringValue: "location")

    static let _knownKeys: Set<Swift.String> = [
      "source",
      "target",
      "processes",
      "dependencyInfo",
      "depth",
      "location",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.source = try container.decodeIfPresent(EntityReference.self, forKey: .source)
    self.target = try container.decodeIfPresent(EntityReference.self, forKey: .target)
    if let value = try container.decodeIfPresent(
      [LineageLink.LineageProcess].self, forKey: .processes)
    {
      self.processes = value
    }
    if let value = try container.decodeIfPresent(
      [LineageLink.DependencyInfo].self, forKey: .dependencyInfo)
    {
      self.dependencyInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .depth) {
      self.depth = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encodeIfPresent(self.target, forKey: .target)
    try container.encode(self.processes, forKey: .processes)
    try container.encode(self.dependencyInfo, forKey: .dependencyInfo)
    try container.encode(self.depth, forKey: .depth)
    try container.encode(self.location, forKey: .location)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Process metadata for the link.
  public struct LineageProcess: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Process that created the link.
    public var process: Process? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LineageProcess`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LineageProcess().with { $0.process = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let process = CodingKeys(stringValue: "process")

      static let _knownKeys: Set<Swift.String> = [
        "process"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.process = try container.decodeIfPresent(Process.self, forKey: .process)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.process, forKey: .process)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink.LineageProcess"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Dependency info describes how one entity is dependent on another.
  public struct DependencyInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The type of dependency.
    public var dependencyType: DependencyType = DependencyType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DependencyInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DependencyInfo().with { $0.dependencyType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dependencyType = CodingKeys(stringValue: "dependencyType")

      static let _knownKeys: Set<Swift.String> = [
        "dependencyType"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(DependencyType.self, forKey: .dependencyType) {
        self.dependencyType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyType, forKey: .dependencyType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink.DependencyInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
