// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Lineage is used to track data flows between assets over time. You can
/// create [LineageEvents][google.cloud.datacatalog.lineage.v1.LineageEvent]
/// to record lineage between multiple sources and a single target, for
/// example, when table data is based on data from multiple tables.
///
/// [google.cloud.datacatalog.lineage.v1.LineageEvent]: <doc:LineageEvent>
///
/// @Snippet(path: "LineageQuickstart")
public final class LineageClient: Clients.LineageProtocol, Sendable {
  let inner: any Clients.LineageStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `LineageClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.LineageStub = try Clients.LineageTransport(options)
    inner = Clients.LineageRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LineageLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates new lineage events together with their parents: process and run.
  /// Updates the process and run if they already exist.
  /// Mapped from Open Lineage specification:
  /// https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json.
  ///
  /// @Snippet(path: "Lineage_ProcessOpenLineageRunEvent")
  public func processOpenLineageRunEvent(
    request: ProcessOpenLineageRunEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse {
    try await self.inner.processOpenLineageRunEvent(request: request, options: options)
  }

  /// Creates a new process.
  ///
  /// @Snippet(path: "Lineage_CreateProcess")
  public func createProcess(
    request: CreateProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    try await self.inner.createProcess(request: request, options: options)
  }

  /// Updates a process.
  ///
  /// @Snippet(path: "Lineage_UpdateProcess")
  public func updateProcess(
    request: UpdateProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    try await self.inner.updateProcess(request: request, options: options)
  }

  /// Gets the details of the specified process.
  ///
  /// @Snippet(path: "Lineage_GetProcess")
  public func getProcess(
    request: GetProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    try await self.inner.getProcess(request: request, options: options)
  }

  /// List processes in the given project and location. List order is descending
  /// by insertion time.
  ///
  /// @Snippet(path: "Lineage_ListProcesses")
  public func listProcesses(
    request: ListProcessesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse {
    try await self.inner.listProcesses(request: request, options: options)
  }

  /// Deletes the process with the specified name.
  ///
  /// @Snippet(path: "Lineage_DeleteProcess")
  public func deleteProcess(
    request: DeleteProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteProcess(request: request, options: options)
  }

  /// Deletes the process with the specified name.
  ///
  /// @Snippet(path: "Lineage_DeleteProcess")
  public func deleteProcessPollingUntilDone(
    request: DeleteProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteProcess(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a new run.
  ///
  /// @Snippet(path: "Lineage_CreateRun")
  public func createRun(
    request: CreateRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    try await self.inner.createRun(request: request, options: options)
  }

  /// Updates a run.
  ///
  /// @Snippet(path: "Lineage_UpdateRun")
  public func updateRun(
    request: UpdateRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    try await self.inner.updateRun(request: request, options: options)
  }

  /// Gets the details of the specified run.
  ///
  /// @Snippet(path: "Lineage_GetRun")
  public func getRun(
    request: GetRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    try await self.inner.getRun(request: request, options: options)
  }

  /// Lists runs in the given project and location. List order is descending by
  /// `start_time`.
  ///
  /// @Snippet(path: "Lineage_ListRuns")
  public func listRuns(
    request: ListRunsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListRunsResponse {
    try await self.inner.listRuns(request: request, options: options)
  }

  /// Deletes the run with the specified name.
  ///
  /// @Snippet(path: "Lineage_DeleteRun")
  public func deleteRun(
    request: DeleteRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRun(request: request, options: options)
  }

  /// Deletes the run with the specified name.
  ///
  /// @Snippet(path: "Lineage_DeleteRun")
  public func deleteRunPollingUntilDone(
    request: DeleteRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteRun(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a new lineage event.
  ///
  /// @Snippet(path: "Lineage_CreateLineageEvent")
  public func createLineageEvent(
    request: CreateLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    try await self.inner.createLineageEvent(request: request, options: options)
  }

  /// Gets details of a specified lineage event.
  ///
  /// @Snippet(path: "Lineage_GetLineageEvent")
  public func getLineageEvent(
    request: GetLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    try await self.inner.getLineageEvent(request: request, options: options)
  }

  /// Lists lineage events in the given project and location. The list order is
  /// not defined.
  ///
  /// @Snippet(path: "Lineage_ListLineageEvents")
  public func listLineageEvents(
    request: ListLineageEventsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse {
    try await self.inner.listLineageEvents(request: request, options: options)
  }

  /// Deletes the lineage event with the specified name.
  ///
  /// @Snippet(path: "Lineage_DeleteLineageEvent")
  public func deleteLineageEvent(
    request: DeleteLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteLineageEvent(request: request, options: options)
  }

  /// Retrieve a list of links connected to a specific asset.
  /// Links represent the data flow between **source** (upstream)
  /// and **target** (downstream) assets in transformation pipelines.
  /// Links are stored in the same project as the Lineage Events that create
  /// them.
  ///
  /// You can retrieve links in every project where you have the
  /// `datalineage.events.get` permission. The project provided in the URL
  /// is used for Billing and Quota.
  ///
  /// @Snippet(path: "Lineage_SearchLinks")
  public func searchLinks(
    request: SearchLinksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse {
    try await self.inner.searchLinks(request: request, options: options)
  }

  /// Retrieve information about LineageProcesses associated with specific
  /// links. LineageProcesses are transformation pipelines that result in data
  /// flowing from **source** to **target** assets. Links between assets
  /// represent this operation.
  ///
  /// If you have specific link names, you can use this method to
  /// verify which LineageProcesses contribute to creating those links.
  /// See the
  /// [SearchLinks][google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]
  /// method for more information on how to retrieve link name.
  ///
  /// You can retrieve the LineageProcess information in every project where you
  /// have the `datalineage.events.get` permission. The project provided in the
  /// URL is used for Billing and Quota.
  ///
  /// [google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]: <doc:LineageClient/searchLinks(request:options:)>
  ///
  /// @Snippet(path: "Lineage_BatchSearchLinkProcesses")
  public func batchSearchLinkProcesses(
    request: BatchSearchLinkProcessesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse {
    try await self.inner.batchSearchLinkProcesses(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lineage_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lineage_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lineage_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lineage_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LineageClient`.
  ///
  /// To mock `LineageClient` change your functions to receive
  /// `some LineageProtocol` or `any LineageProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LineageProtocol: Sendable {
    /// See `LineageClient.processOpenLineageRunEvent`.
    func processOpenLineageRunEvent(
      request: ProcessOpenLineageRunEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse

    /// See `LineageClient.createProcess`.
    func createProcess(
      request: CreateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    /// See `LineageClient.updateProcess`.
    func updateProcess(
      request: UpdateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    /// See `LineageClient.getProcess`.
    func getProcess(
      request: GetProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    /// See `LineageClient.listProcesses`.
    func listProcesses(
      request: ListProcessesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse

    /// See `LineageClient.deleteProcess`.
    func deleteProcess(
      request: DeleteProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LineageClient.deleteProcess`.
    func deleteProcessPollingUntilDone(
      request: DeleteProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LineageClient.createRun`.
    func createRun(
      request: CreateRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    /// See `LineageClient.updateRun`.
    func updateRun(
      request: UpdateRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    /// See `LineageClient.getRun`.
    func getRun(
      request: GetRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    /// See `LineageClient.listRuns`.
    func listRuns(
      request: ListRunsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListRunsResponse

    /// See `LineageClient.deleteRun`.
    func deleteRun(
      request: DeleteRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LineageClient.deleteRun`.
    func deleteRunPollingUntilDone(
      request: DeleteRunRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LineageClient.createLineageEvent`.
    func createLineageEvent(
      request: CreateLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent

    /// See `LineageClient.getLineageEvent`.
    func getLineageEvent(
      request: GetLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent

    /// See `LineageClient.listLineageEvents`.
    func listLineageEvents(
      request: ListLineageEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse

    /// See `LineageClient.deleteLineageEvent`.
    func deleteLineageEvent(
      request: DeleteLineageEventRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `LineageClient.searchLinks`.
    func searchLinks(
      request: SearchLinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse

    /// See `LineageClient.batchSearchLinkProcesses`.
    func batchSearchLinkProcesses(
      request: BatchSearchLinkProcessesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse

    /// See `LineageClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `LineageClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `LineageClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.LineageProtocol {
  public func processOpenLineageRunEvent(request: ProcessOpenLineageRunEventRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse
  {
    try await self.processOpenLineageRunEvent(request: request, options: .init())
  }

  public func processOpenLineageRunEvent(
    request: ProcessOpenLineageRunEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func processOpenLineageRunEvent(
    parent: Swift.String,
    openLineage: GoogleWKT.WKTStruct?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse {
    let request = ProcessOpenLineageRunEventRequest().with {
      $0.parent = parent
      $0.openLineage = openLineage
    }
    return try await self.processOpenLineageRunEvent(request: request)
  }

  public func createProcess(request: CreateProcessRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.Process
  {
    try await self.createProcess(request: request, options: .init())
  }

  public func createProcess(
    request: CreateProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createProcess(
    parent: Swift.String,
    process: Process?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    let request = CreateProcessRequest().with {
      $0.parent = parent
      $0.process = process
    }
    return try await self.createProcess(request: request)
  }

  public func updateProcess(request: UpdateProcessRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.Process
  {
    try await self.updateProcess(request: request, options: .init())
  }

  public func updateProcess(
    request: UpdateProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateProcess(
    process: Process?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    let request = UpdateProcessRequest().with {
      $0.process = process
      $0.updateMask = updateMask
    }
    return try await self.updateProcess(request: request)
  }

  public func getProcess(request: GetProcessRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.Process
  {
    try await self.getProcess(request: request, options: .init())
  }

  public func getProcess(
    request: GetProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getProcess(
    name: Swift.String,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Process {
    let request = GetProcessRequest().with {
      $0.name = name
    }
    return try await self.getProcess(request: request)
  }

  public func listProcesses(request: ListProcessesRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse
  {
    try await self.listProcesses(request: request, options: .init())
  }

  public func listProcesses(
    request: ListProcessesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listProcessesByItems(
    request: ListProcessesRequest
  ) -> any AsyncSequence<Process, Swift.Error> & Sendable {
    self.listProcessesByItems(request: request, options: .init())
  }

  /// List processes in the given project and location. List order is descending
  /// by insertion time.
  ///
  /// @Snippet(path: "Lineage_ListProcesses")
  public func listProcessesByItems(
    request: ListProcessesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Process, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse in
      var request = request
      request.pageToken = token
      return try await self.listProcesses(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProcessesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Process, Swift.Error> & Sendable {
    let request = ListProcessesRequest().with {
      $0.parent = parent
    }
    return self.listProcessesByItems(request: request)
  }

  public func deleteProcess(request: DeleteProcessRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteProcess(request: request, options: .init())
  }

  public func deleteProcess(
    request: DeleteProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteProcessPollingUntilDone(request: DeleteProcessRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteProcessPollingUntilDone(request: request, options: .init())
  }

  public func deleteProcessPollingUntilDone(
    request: DeleteProcessRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteProcessPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteProcessRequest().with {
      $0.name = name
    }
    return try await self.deleteProcessPollingUntilDone(request: request)
  }

  public func createRun(request: CreateRunRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.Run
  {
    try await self.createRun(request: request, options: .init())
  }

  public func createRun(
    request: CreateRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createRun(
    parent: Swift.String,
    run: Run?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    let request = CreateRunRequest().with {
      $0.parent = parent
      $0.run = run
    }
    return try await self.createRun(request: request)
  }

  public func updateRun(request: UpdateRunRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.Run
  {
    try await self.updateRun(request: request, options: .init())
  }

  public func updateRun(
    request: UpdateRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateRun(
    run: Run?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    let request = UpdateRunRequest().with {
      $0.run = run
      $0.updateMask = updateMask
    }
    return try await self.updateRun(request: request)
  }

  public func getRun(request: GetRunRequest) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    try await self.getRun(request: request, options: .init())
  }

  public func getRun(
    request: GetRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRun(
    name: Swift.String,
  ) async throws -> GoogleCloudDataCatalogLineageV1.Run {
    let request = GetRunRequest().with {
      $0.name = name
    }
    return try await self.getRun(request: request)
  }

  public func listRuns(request: ListRunsRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.ListRunsResponse
  {
    try await self.listRuns(request: request, options: .init())
  }

  public func listRuns(
    request: ListRunsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListRunsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRunsByItems(
    request: ListRunsRequest
  ) -> any AsyncSequence<Run, Swift.Error> & Sendable {
    self.listRunsByItems(request: request, options: .init())
  }

  /// Lists runs in the given project and location. List order is descending by
  /// `start_time`.
  ///
  /// @Snippet(path: "Lineage_ListRuns")
  public func listRunsByItems(
    request: ListRunsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Run, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudDataCatalogLineageV1.ListRunsResponse in
      var request = request
      request.pageToken = token
      return try await self.listRuns(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRunsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Run, Swift.Error> & Sendable {
    let request = ListRunsRequest().with {
      $0.parent = parent
    }
    return self.listRunsByItems(request: request)
  }

  public func deleteRun(request: DeleteRunRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteRun(request: request, options: .init())
  }

  public func deleteRun(
    request: DeleteRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteRunPollingUntilDone(request: DeleteRunRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteRunPollingUntilDone(request: request, options: .init())
  }

  public func deleteRunPollingUntilDone(
    request: DeleteRunRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRunPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteRunRequest().with {
      $0.name = name
    }
    return try await self.deleteRunPollingUntilDone(request: request)
  }

  public func createLineageEvent(request: CreateLineageEventRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.LineageEvent
  {
    try await self.createLineageEvent(request: request, options: .init())
  }

  public func createLineageEvent(
    request: CreateLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createLineageEvent(
    parent: Swift.String,
    lineageEvent: LineageEvent?,
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    let request = CreateLineageEventRequest().with {
      $0.parent = parent
      $0.lineageEvent = lineageEvent
    }
    return try await self.createLineageEvent(request: request)
  }

  public func getLineageEvent(request: GetLineageEventRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.LineageEvent
  {
    try await self.getLineageEvent(request: request, options: .init())
  }

  public func getLineageEvent(
    request: GetLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLineageEvent(
    name: Swift.String,
  ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent {
    let request = GetLineageEventRequest().with {
      $0.name = name
    }
    return try await self.getLineageEvent(request: request)
  }

  public func listLineageEvents(request: ListLineageEventsRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse
  {
    try await self.listLineageEvents(request: request, options: .init())
  }

  public func listLineageEvents(
    request: ListLineageEventsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLineageEventsByItems(
    request: ListLineageEventsRequest
  ) -> any AsyncSequence<LineageEvent, Swift.Error> & Sendable {
    self.listLineageEventsByItems(request: request, options: .init())
  }

  /// Lists lineage events in the given project and location. The list order is
  /// not defined.
  ///
  /// @Snippet(path: "Lineage_ListLineageEvents")
  public func listLineageEventsByItems(
    request: ListLineageEventsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<LineageEvent, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLineageEvents(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLineageEventsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<LineageEvent, Swift.Error> & Sendable {
    let request = ListLineageEventsRequest().with {
      $0.parent = parent
    }
    return self.listLineageEventsByItems(request: request)
  }

  public func deleteLineageEvent(request: DeleteLineageEventRequest) async throws {
    try await self.deleteLineageEvent(request: request, options: .init())
  }

  public func deleteLineageEvent(
    request: DeleteLineageEventRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteLineageEvent(
    name: Swift.String,
  ) async throws {
    let request = DeleteLineageEventRequest().with {
      $0.name = name
    }
    try await self.deleteLineageEvent(request: request)
  }

  public func searchLinks(request: SearchLinksRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse
  {
    try await self.searchLinks(request: request, options: .init())
  }

  public func searchLinks(
    request: SearchLinksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchLinksByItems(
    request: SearchLinksRequest
  ) -> any AsyncSequence<Link, Swift.Error> & Sendable {
    self.searchLinksByItems(request: request, options: .init())
  }

  /// Retrieve a list of links connected to a specific asset.
  /// Links represent the data flow between **source** (upstream)
  /// and **target** (downstream) assets in transformation pipelines.
  /// Links are stored in the same project as the Lineage Events that create
  /// them.
  ///
  /// You can retrieve links in every project where you have the
  /// `datalineage.events.get` permission. The project provided in the URL
  /// is used for Billing and Quota.
  ///
  /// @Snippet(path: "Lineage_SearchLinks")
  public func searchLinksByItems(
    request: SearchLinksRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Link, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse in
      var request = request
      request.pageToken = token
      return try await self.searchLinks(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func batchSearchLinkProcesses(request: BatchSearchLinkProcessesRequest) async throws
    -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse
  {
    try await self.batchSearchLinkProcesses(request: request, options: .init())
  }

  public func batchSearchLinkProcesses(
    request: BatchSearchLinkProcessesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchSearchLinkProcessesByItems(
    request: BatchSearchLinkProcessesRequest
  ) -> any AsyncSequence<ProcessLinks, Swift.Error> & Sendable {
    self.batchSearchLinkProcessesByItems(request: request, options: .init())
  }

  /// Retrieve information about LineageProcesses associated with specific
  /// links. LineageProcesses are transformation pipelines that result in data
  /// flowing from **source** to **target** assets. Links between assets
  /// represent this operation.
  ///
  /// If you have specific link names, you can use this method to
  /// verify which LineageProcesses contribute to creating those links.
  /// See the
  /// [SearchLinks][google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]
  /// method for more information on how to retrieve link name.
  ///
  /// You can retrieve the LineageProcess information in every project where you
  /// have the `datalineage.events.get` permission. The project provided in the
  /// URL is used for Billing and Quota.
  ///
  /// [google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]: <doc:LineageClient/searchLinks(request:options:)>
  ///
  /// @Snippet(path: "Lineage_BatchSearchLinkProcesses")
  public func batchSearchLinkProcessesByItems(
    request: BatchSearchLinkProcessesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ProcessLinks, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse in
      var request = request
      request.pageToken = token
      return try await self.batchSearchLinkProcesses(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lineage_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
