// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Origin of a process.
public struct Origin: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Type of the source.
  ///
  /// Use of a source_type other than `CUSTOM` for process creation
  /// or updating is highly discouraged. It might be restricted in the future
  /// without notice. There will be increase in cost if you use any of the source
  /// types other than `CUSTOM`.
  public var sourceType: Origin.SourceType = Origin.SourceType()

  /// If the source_type isn't CUSTOM, the value of this field should be a Google
  /// Cloud resource name of the system, which reports lineage. The project and
  /// location parts of the resource name must match the project and location of
  /// the lineage resource being created. Examples:
  ///
  /// - `{source_type: COMPOSER, name:
  ///   "projects/foo/locations/us/environments/bar"}`
  /// - `{source_type: BIGQUERY, name: "projects/foo/locations/eu"}`
  /// - `{source_type: CUSTOM,   name: "myCustomIntegration"}`
  public var name: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Origin`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Origin().with { $0.sourceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceType = CodingKeys(stringValue: "sourceType")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "sourceType",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Origin.SourceType.self, forKey: .sourceType) {
      self.sourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceType, forKey: .sourceType)
    try container.encode(self.name, forKey: .name)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the source of a process.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SourceType: Codable, Equatable, Hashable, Sendable {
    /// Source is Unspecified
    case unspecified
    /// A custom source
    case custom
    /// BigQuery
    case bigquery
    /// Data Fusion
    case dataFusion
    /// Composer
    case composer
    /// Looker Studio
    case lookerStudio
    /// Dataproc
    case dataproc
    /// Vertex AI
    case vertexAi
    /// Dataflow
    case dataflow
    /// Looker Core
    case lookerCore
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .custom: return 1
      case .bigquery: return 2
      case .dataFusion: return 3
      case .composer: return 4
      case .lookerStudio: return 5
      case .dataproc: return 6
      case .vertexAi: return 7
      case .dataflow: return 8
      case .lookerCore: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SOURCE_TYPE_UNSPECIFIED"
      case .custom: return "CUSTOM"
      case .bigquery: return "BIGQUERY"
      case .dataFusion: return "DATA_FUSION"
      case .composer: return "COMPOSER"
      case .lookerStudio: return "LOOKER_STUDIO"
      case .dataproc: return "DATAPROC"
      case .vertexAi: return "VERTEX_AI"
      case .dataflow: return "DATAFLOW"
      case .lookerCore: return "LOOKER_CORE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "CUSTOM": self = .custom
      case "BIGQUERY": self = .bigquery
      case "DATA_FUSION": self = .dataFusion
      case "COMPOSER": self = .composer
      case "LOOKER_STUDIO": self = .lookerStudio
      case "DATAPROC": self = .dataproc
      case "VERTEX_AI": self = .vertexAi
      case "DATAFLOW": self = .dataflow
      case "LOOKER_CORE": self = .lookerCore
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .custom
      case 2: self = .bigquery
      case 3: self = .dataFusion
      case 4: self = .composer
      case 5: self = .lookerStudio
      case 6: self = .dataproc
      case 7: self = .vertexAi
      case 8: self = .dataflow
      case 9: self = .lookerCore
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SOURCE_TYPE_UNSPECIFIED")
      case .custom: return try container.encode("CUSTOM")
      case .bigquery: return try container.encode("BIGQUERY")
      case .dataFusion: return try container.encode("DATA_FUSION")
      case .composer: return try container.encode("COMPOSER")
      case .lookerStudio: return try container.encode("LOOKER_STUDIO")
      case .dataproc: return try container.encode("DATAPROC")
      case .vertexAi: return try container.encode("VERTEX_AI")
      case .dataflow: return try container.encode("DATAFLOW")
      case .lookerCore: return try container.encode("LOOKER_CORE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.Origin"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
