// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Links associated with a specific process.
public struct ProcessLinks: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The process name in the format of
  /// `projects/{project}/locations/{location}/processes/{process}`.
  public var process: Swift.String = Swift.String()

  /// An array containing link details objects of the links provided in
  /// the original request.
  ///
  /// A single process can result in creating multiple links.
  /// If any of the links you provide in the request are created by
  /// the same process, they all are included in this array.
  public var links: [ProcessLinkInfo] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProcessLinks`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessLinks().with { $0.process = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let process = CodingKeys(stringValue: "process")
    static let links = CodingKeys(stringValue: "links")

    static let _knownKeys: Set<Swift.String> = [
      "process",
      "links",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .process) {
      self.process = value
    }
    if let value = try container.decodeIfPresent([ProcessLinkInfo].self, forKey: .links) {
      self.links = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.process, forKey: .process)
    try container.encode(self.links, forKey: .links)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ProcessLinks`: `"type.googleapis.com/google.cloud.datacatalog.lineage.v1.ProcessLinks"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.ProcessLinks"
  }

  /// Initialize an instance of `ProcessLinks` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.datacatalog.lineage.v1.ProcessLinks"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ProcessLinks` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
