// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [SearchLinks][google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]: <doc:LineageClient/searchLinks(request:options:)>
public struct SearchLinksRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The project and location you want search in.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of links to return in a single page of the
  /// response. A page may contain fewer links than this value. If unspecified,
  /// at most 10 links are returned.
  ///
  /// Maximum value is 100; values greater than 100 are reduced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token received from a previous `SearchLinksRequest`
  /// call. Use it to get the next page.
  ///
  /// When requesting subsequent pages of a response, remember that
  /// all parameters must match the values you provided
  /// in the original request.
  public var pageToken: Swift.String = Swift.String()

  /// The asset for which you want to retrieve links.
  public var criteria: OneOf_Criteria? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchLinksRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchLinksRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let source = CodingKeys(stringValue: "source")
    static let target = CodingKeys(stringValue: "target")
    static let sources = CodingKeys(stringValue: "sources")
    static let targets = CodingKeys(stringValue: "targets")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "source",
      "target",
      "sources",
      "targets",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }

    var criteria: OneOf_Criteria? = nil
    let criteriaCheckAndSet = {
      if criteria != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'criteria'"))
      }
      criteria = $0
    }
    if let source = try container.decodeIfPresent(EntityReference?.self, forKey: .source) {
      try criteriaCheckAndSet(.source(source))
    }
    if let target = try container.decodeIfPresent(EntityReference?.self, forKey: .target) {
      try criteriaCheckAndSet(.target(target))
    }
    if let sources = try container.decodeIfPresent(MultipleEntityReference?.self, forKey: .sources)
    {
      try criteriaCheckAndSet(.sources(sources))
    }
    if let targets = try container.decodeIfPresent(MultipleEntityReference?.self, forKey: .targets)
    {
      try criteriaCheckAndSet(.targets(targets))
    }
    self.criteria = criteria
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)

    if let choice = self.criteria {
      switch choice {
      case .source(let value):
        try container.encode(value, forKey: .source)
      case .target(let value):
        try container.encode(value, forKey: .target)
      case .sources(let value):
        try container.encode(value, forKey: .sources)
      case .targets(let value):
        try container.encode(value, forKey: .targets)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The asset for which you want to retrieve links.
  public enum OneOf_Criteria: Codable, Equatable, Sendable {
    /// Optional. Send asset information in the **source** field to retrieve all
    /// links that lead from the specified asset to downstream assets.
    indirect case source(EntityReference?)
    /// Optional. Send asset information in the **target** field to retrieve all
    /// links that lead from upstream assets to the specified asset.
    indirect case target(EntityReference?)
    /// Optional. Send a list of asset information in the **sources** field to
    /// retrieve all links that lead from the specified assets to downstream
    /// assets. This field is similar to the `source`
    /// [source][google.cloud.datacatalog.lineage.v1.SearchLinksRequest.source]
    /// field but allows providing multiple entities.
    /// All entities within the `MultipleEntityReference` must have the same
    /// `fully_qualified_name`.
    ///
    /// [google.cloud.datacatalog.lineage.v1.SearchLinksRequest.source]: <doc:SearchLinksRequest/OneOf_Criteria/source(_:)>
    indirect case sources(MultipleEntityReference?)
    /// Optional. Send a list of asset information in the **targets** field to
    /// retrieve all links that lead from upstream assets to the specified
    /// assets. This field is similar to the `target`
    /// [target][google.cloud.datacatalog.lineage.v1.SearchLinksRequest.target]
    /// field but allows providing multiple entities.
    /// All entities within the `MultipleEntityReference` must have the same
    /// `fully_qualified_name`.
    ///
    /// [google.cloud.datacatalog.lineage.v1.SearchLinksRequest.target]: <doc:SearchLinksRequest/OneOf_Criteria/target(_:)>
    indirect case targets(MultipleEntityReference?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLinksRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
