// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [UpdateProcess][google.cloud.datacatalog.lineage.v1.Lineage.UpdateProcess].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.UpdateProcess]: <doc:LineageClient/updateProcess(request:options:)>
public struct UpdateProcessRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The lineage process to update.
  ///
  /// The process's `name` field is used to identify the process to update.
  public var process: Process? = nil

  /// Optional. The list of fields to update. Currently not used. The whole
  /// message is updated.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// Optional. If set to true and the process is not found, the request inserts
  /// it.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. A unique identifier for this request. Restricted to 36 ASCII
  /// characters. A random UUID is recommended. This request is idempotent only
  /// if a `request_id` is provided.
  public var requestId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateProcessRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateProcessRequest().with { $0.process = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let process = CodingKeys(stringValue: "process")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let allowMissing = CodingKeys(stringValue: "allowMissing")
    static let requestId = CodingKeys(stringValue: "requestId")

    static let _knownKeys: Set<Swift.String> = [
      "process",
      "updateMask",
      "allowMissing",
      "requestId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.process = try container.decodeIfPresent(Process.self, forKey: .process)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissing) {
      self.allowMissing = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.process, forKey: .process)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.allowMissing, forKey: .allowMissing)
    try container.encode(self.requestId, forKey: .requestId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.UpdateProcessRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
